# Change these first
owner: FirenzeDigital # Your GitHub organization or username, where this repository lives
repo: upptime-holycrm # The name of this repository

sites:
  # HolyCRM.app Website
  # - name: HolyCRM.app Website
  #   url: https://holycrm.app
  # HolyCRM.app production instances
  # - name: HolyCRM.app production frontend instance
  #   url: https://app.holycrm.app
  # - name: HolyCRM.app production backend instance
  #   url: https://pb.holycrm.app/backend/api/health
  # HolyCRM.app dev instances
  - name: HolyCRM.app dev frontend instance
    url: https://app-dev.holycrm.app
  - name: HolyCRM.app dev backend instance
    url: https://pb-dev.holycrm.app/backend/api/health

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.holycrm.app
  # baseUrl: /your-repo-name
  theme: night
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status - HolyCRM.app
  introTitle: "HolyCRM.app -  **Upptime** Status page."
  introMessage: This is a status page which uses **real-time** data multiples endpoints. If you have any issues, please contact us via email to support@holycrm.app
  # navbar:
  #   - title: Status
  #     href: /
  #   - title: GitHub
  #     href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
